/** レーティング枠画像の固定論理幅 */
export const RATING_IMAGE_WIDTH_PX = 1_024
/** レーティング枠画像を原寸で出力するピクセル比 */
export const RATING_IMAGE_PIXEL_RATIO = 1
/** レーティング枠JPEG画像の圧縮品質 */
export const RATING_IMAGE_JPEG_QUALITY = 0.9

/** レーティング枠画像化プレビューで使用する文言 */
export const RATING_IMAGE_COPY = {
  openPreview: '画像化',
  dialogTitle: '画像化プレビュー',
  dialogDescription: '現在のテーマとジャケット表示設定で画像を作成します。',
  preparingPreview: '画像化プレビューを準備中',
  bestHeading: 'ベスト枠',
  newHeading: '新曲枠',
  averageLabel: 'Avg.',
  ratingLabel: 'RATING',
  overPowerLabel: 'OP',
  overPowerPercentLabel: 'OP%',
  generatedBy: 'Generated by ChuniSupport',
  close: '閉じる',
  share: '共有',
  preparingShare: '共有画像を準備中',
  sharing: '画像を共有中',
  shareError: '画像の共有に失敗しました。',
  copy: 'コピー',
  copying: 'コピー中',
  copied: 'コピーしました',
  copyError: '画像のコピーに失敗しました。',
  download: 'ダウンロード',
  downloading: '画像を作成中',
  downloadError: '画像のダウンロードに失敗しました。',
} as const

/**
 * 空きレーティング枠の読み上げ文言を生成する。
 *
 * @param slotNumber - 1始まりの枠番号。
 * @returns 空き枠であることを示す読み上げ文言。
 */
export const buildEmptyRatingSlotLabel = (slotNumber: number): string => `${slotNumber}番は空き枠`
